services:

  my_nuxt_docker:
    build:
      context: ./simple-nuxt
    working_dir: /app
    volumes:
      - ./simple-nuxt:/app
      - app_node_modules:/app/node_modules
      - app_dotnuxt:/app/.nuxt
    command: [yarn, dev]
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0

volumes:
  app_node_modules:
  app_dotnuxt:
